namespace: felixfontein
name: versioning_test_collection
version: 2.3.0-pre
readme: README.md
authors:
  - Felix Fontein (https://github.com/felixfontein)
description: null
license_file: COPYING
tags: [felixfontein]
dependencies: {}
repository: https://github.com/felixfontein/ansible-versioning_test_collection
homepage: https://github.com/felixfontein/ansible-versioning_test_collection
issues: https://github.com/felixfontein/ansible-versioning_test_collection/issues
build_ignore:
  - 'felixfontein-versioning_test_collection-*.tar.gz'
  - .gitignore
