changelog_filename_template: CHANGELOG-v%s.rst
changelog_filename_version_depth: 1
changes_file: changelog.yaml
changes_format: combined
keep_fragments: false
new_plugins_after_name: removed_features
notesdir: fragments
pre_release_tag_re: (?P<pre_release>(?:[ab]|rc)+\d*)$
prelude_section_name: release_summary
prelude_section_title: Release Summary
release_tag_re: (v(?:[\d.ab\-]|rc)+)
sections:
- - major_changes
  - Major Changes
- - minor_changes
  - Minor Changes
- - deprecated_features
  - Deprecated Features
- - removed_features
  - Removed Features (previously deprecated)
- - bugfixes
  - Bugfixes
- - known_issues
  - Known Issues
title: Felix Fontein's Amazing Versioning Test Collection
